/**
 * Curated NHL legends dataset for the all-time roster-building game (casual fans).
 *
 * Every player here is a household name / Hall of Famer, chosen so a casual fan
 * recognizes them on sight. The game builds a roster needing one each of
 * C / LW / RW / D / D / G, each from a DIFFERENT decade, so coverage is the
 * priority: every era (1960s-2020s) carries multiple players at each of the
 * five positions.
 *
 * STAT CONVENTIONS
 *   Numbers are PER-SEASON PEAK — one representative great season, not career
 *   totals. They are intentionally ERA-REALISTIC and NOT flattened: 1980s stars
 *   carry their genuinely enormous raw totals, 1960s-70s Original Six legends
 *   carry lower totals, the 2000s "dead puck era" is suppressed, and the modern
 *   game is moderate. The game applies its own era adjustment downstream.
 *
 *   Skaters (C, LW, RW, D): { g, a, p, pm }  // p ~= g + a, pm = plus-minus
 *   Goalies (G):            { w, svp, gaa, so } // svp/gaa decimals; w/so ints
 *   (Save% is only meaningful from ~1983 on; older goalies get a plausible svp
 *    plus a low gaa and high wins/shutouts.)
 *
 * RATING (0-100, vs all-time peers)
 *   Inner-circle GOATs highest (Gretzky 99, Orr 97, Lemieux 96, Howe 95,
 *   Roy/Hasek 94); clear HOF 80-92; very good / borderline 72-80.
 *
 * FRANCHISE SLUGS map each player to where he was most iconic. Relocations:
 *   Quebec Nordiques -> avalanche; Hartford Whalers -> hurricanes;
 *   Minnesota North Stars -> stars; Colorado Rockies -> devils;
 *   Winnipeg/Atlanta -> jets. Gretzky's peak -> oilers.
 *
 * ERA ids use the decade of the player's PEAK. Original Six legends whose
 * careers reached the 1960s (Howe, Richard, Beliveau, Hull) live in "1960s".
 */
export interface NhlPlayer {
  name: string; // "Wayne Gretzky"
  team: string; // franchise SLUG from the allowed list
  era: string; // decade id from the allowed list
  pos: string; // one of: C LW RW D G
  stats: Record<string, number>; // role-specific, see schema
  rating?: number; // 0-100 all-time relative strength
  notable?: string; // short flavor, e.g. "HOF, 4x Stanley Cup, 9x MVP"
}

export const NHL_PLAYERS: NhlPlayer[] = [
  // =========================================================================
  // 1960s — Original Six era. Lower totals; goalies get low gaa, high wins/SO.
  // =========================================================================

  // Centers
  {
    name: "Jean Beliveau",
    team: "canadiens",
    era: "1960s",
    pos: "C",
    stats: { g: 47, a: 51, p: 98, pm: 30 },
    rating: 91,
    notable: "HOF, 10x Stanley Cup, 2x MVP",
  },
  {
    name: "Stan Mikita",
    team: "blackhawks",
    era: "1960s",
    pos: "C",
    stats: { g: 40, a: 57, p: 97, pm: 28 },
    rating: 90,
    notable: "HOF, Stanley Cup, 4x Art Ross, 2x MVP",
  },
  {
    name: "Henri Richard",
    team: "canadiens",
    era: "1960s",
    pos: "C",
    stats: { g: 30, a: 50, p: 80, pm: 27 },
    rating: 84,
    notable: "HOF, 11x Stanley Cup champion",
  },
  {
    name: "Alex Delvecchio",
    team: "redwings",
    era: "1960s",
    pos: "C",
    stats: { g: 27, a: 56, p: 83, pm: 22 },
    rating: 82,
    notable: "HOF, Stanley Cup, 3x Lady Byng",
  },
  {
    name: "Norm Ullman",
    team: "redwings",
    era: "1960s",
    pos: "C",
    stats: { g: 42, a: 41, p: 83, pm: 20 },
    rating: 80,
    notable: "HOF, 4x All-Star",
  },

  // Left Wings
  {
    name: "Bobby Hull",
    team: "blackhawks",
    era: "1960s",
    pos: "LW",
    stats: { g: 58, a: 39, p: 97, pm: 34 },
    rating: 93,
    notable: "HOF, Stanley Cup, 3x Art Ross, 2x MVP",
  },
  {
    name: "Frank Mahovlich",
    team: "mapleleafs",
    era: "1960s",
    pos: "LW",
    stats: { g: 48, a: 36, p: 84, pm: 28 },
    rating: 86,
    notable: "HOF, 6x Stanley Cup champion",
  },
  {
    name: "Dean Prentice",
    team: "rangers",
    era: "1960s",
    pos: "LW",
    stats: { g: 32, a: 34, p: 66, pm: 16 },
    rating: 76,
    notable: "1000+ career games, All-Star",
  },

  // Right Wings
  {
    name: "Gordie Howe",
    team: "redwings",
    era: "1960s",
    pos: "RW",
    stats: { g: 49, a: 46, p: 95, pm: 40 },
    rating: 95,
    notable: "HOF, 4x Stanley Cup, 6x Art Ross, 6x MVP",
  },
  {
    name: "Maurice Richard",
    team: "canadiens",
    era: "1960s",
    pos: "RW",
    stats: { g: 50, a: 25, p: 75, pm: 30 },
    rating: 92,
    notable: "HOF, 8x Stanley Cup, first to 50 in 50",
  },
  {
    name: "Andy Bathgate",
    team: "rangers",
    era: "1960s",
    pos: "RW",
    stats: { g: 40, a: 44, p: 84, pm: 18 },
    rating: 83,
    notable: "HOF, MVP, Stanley Cup",
  },
  {
    name: "Yvan Cournoyer",
    team: "canadiens",
    era: "1960s",
    pos: "RW",
    stats: { g: 43, a: 36, p: 79, pm: 33 },
    rating: 82,
    notable: "HOF, 10x Stanley Cup champion",
  },
  {
    name: "Bernie Geoffrion",
    team: "canadiens",
    era: "1960s",
    pos: "RW",
    stats: { g: 50, a: 45, p: 95, pm: 26 },
    rating: 84,
    notable: "HOF, 6x Stanley Cup, MVP, Art Ross",
  },

  // Defensemen
  {
    name: "Doug Harvey",
    team: "canadiens",
    era: "1960s",
    pos: "D",
    stats: { g: 9, a: 43, p: 52, pm: 36 },
    rating: 90,
    notable: "HOF, 6x Stanley Cup, 7x Norris",
  },
  {
    name: "Tim Horton",
    team: "mapleleafs",
    era: "1960s",
    pos: "D",
    stats: { g: 12, a: 40, p: 52, pm: 30 },
    rating: 84,
    notable: "HOF, 4x Stanley Cup champion",
  },
  {
    name: "Pierre Pilote",
    team: "blackhawks",
    era: "1960s",
    pos: "D",
    stats: { g: 14, a: 46, p: 60, pm: 28 },
    rating: 83,
    notable: "HOF, Stanley Cup, 3x Norris",
  },
  {
    name: "Harry Howell",
    team: "rangers",
    era: "1960s",
    pos: "D",
    stats: { g: 12, a: 37, p: 49, pm: 20 },
    rating: 80,
    notable: "HOF, Norris Trophy",
  },
  {
    name: "Bill Gadsby",
    team: "redwings",
    era: "1960s",
    pos: "D",
    stats: { g: 9, a: 46, p: 55, pm: 18 },
    rating: 79,
    notable: "HOF, 7x All-Star",
  },

  // Goalies
  {
    name: "Terry Sawchuk",
    team: "redwings",
    era: "1960s",
    pos: "G",
    stats: { w: 44, svp: 0.918, gaa: 2.1, so: 12 },
    rating: 92,
    notable: "HOF, 4x Stanley Cup, 103 career shutouts",
  },
  {
    name: "Glenn Hall",
    team: "blackhawks",
    era: "1960s",
    pos: "G",
    stats: { w: 38, svp: 0.917, gaa: 2.3, so: 8 },
    rating: 90,
    notable: "HOF, Stanley Cup, 3x Vezina, Conn Smythe",
  },
  {
    name: "Jacques Plante",
    team: "canadiens",
    era: "1960s",
    pos: "G",
    stats: { w: 42, svp: 0.92, gaa: 2.2, so: 9 },
    rating: 91,
    notable: "HOF, 6x Stanley Cup, 7x Vezina, pioneered mask",
  },
  {
    name: "Johnny Bower",
    team: "mapleleafs",
    era: "1960s",
    pos: "G",
    stats: { w: 34, svp: 0.916, gaa: 2.4, so: 7 },
    rating: 85,
    notable: "HOF, 4x Stanley Cup champion",
  },
  {
    name: "Gump Worsley",
    team: "canadiens",
    era: "1960s",
    pos: "G",
    stats: { w: 33, svp: 0.915, gaa: 2.3, so: 6 },
    rating: 83,
    notable: "HOF, 4x Stanley Cup, 2x Vezina",
  },

  // =========================================================================
  // 1970s — expansion era opens, Orr revolutionizes D, big Montreal dynasty.
  // =========================================================================

  // Centers
  {
    name: "Phil Esposito",
    team: "bruins",
    era: "1970s",
    pos: "C",
    stats: { g: 76, a: 76, p: 152, pm: 50 },
    rating: 91,
    notable: "HOF, 2x Stanley Cup, 5x Art Ross, 2x MVP",
  },
  {
    name: "Bobby Clarke",
    team: "flyers",
    era: "1970s",
    pos: "C",
    stats: { g: 37, a: 89, p: 126, pm: 47 },
    rating: 88,
    notable: "HOF, 2x Stanley Cup, 3x MVP",
  },
  {
    name: "Gilbert Perreault",
    team: "sabres",
    era: "1970s",
    pos: "C",
    stats: { g: 44, a: 69, p: 113, pm: 35 },
    rating: 85,
    notable: "HOF, French Connection line",
  },
  {
    name: "Darryl Sittler",
    team: "mapleleafs",
    era: "1970s",
    pos: "C",
    stats: { g: 45, a: 72, p: 117, pm: 22 },
    rating: 84,
    notable: "HOF, record 10-point game",
  },
  {
    name: "Bryan Trottier",
    team: "islanders",
    era: "1970s",
    pos: "C",
    stats: { g: 47, a: 87, p: 134, pm: 76 },
    rating: 89,
    notable: "HOF, 4x Stanley Cup, MVP, Art Ross",
  },
  {
    name: "Marcel Dionne",
    team: "kings",
    era: "1970s",
    pos: "C",
    stats: { g: 53, a: 84, p: 137, pm: 20 },
    rating: 88,
    notable: "HOF, Art Ross, 2x Lady Byng",
  },

  // Left Wings
  {
    name: "Bobby Hull",
    team: "blackhawks",
    era: "1970s",
    pos: "LW",
    stats: { g: 51, a: 52, p: 103, pm: 30 },
    rating: 89,
    notable: "HOF, Golden Jet, WHA superstar",
  },
  {
    name: "Steve Shutt",
    team: "canadiens",
    era: "1970s",
    pos: "LW",
    stats: { g: 60, a: 45, p: 105, pm: 60 },
    rating: 82,
    notable: "HOF, 5x Stanley Cup champion",
  },
  {
    name: "Rick Martin",
    team: "sabres",
    era: "1970s",
    pos: "LW",
    stats: { g: 52, a: 43, p: 95, pm: 30 },
    rating: 80,
    notable: "French Connection, 5x All-Star",
  },
  {
    name: "Bill Barber",
    team: "flyers",
    era: "1970s",
    pos: "LW",
    stats: { g: 50, a: 62, p: 112, pm: 35 },
    rating: 81,
    notable: "HOF, 2x Stanley Cup champion",
  },

  // Right Wings
  {
    name: "Guy Lafleur",
    team: "canadiens",
    era: "1970s",
    pos: "RW",
    stats: { g: 60, a: 76, p: 136, pm: 73 },
    rating: 92,
    notable: "HOF, 5x Stanley Cup, 3x Art Ross, 2x MVP",
  },
  {
    name: "Mike Bossy",
    team: "islanders",
    era: "1970s",
    pos: "RW",
    stats: { g: 69, a: 57, p: 126, pm: 38 },
    rating: 90,
    notable: "HOF, 4x Stanley Cup, 9x 50-goal seasons",
  },
  {
    name: "Lanny McDonald",
    team: "flames",
    era: "1970s",
    pos: "RW",
    stats: { g: 47, a: 43, p: 90, pm: 20 },
    rating: 81,
    notable: "HOF, Stanley Cup champion",
  },
  {
    name: "Rod Gilbert",
    team: "rangers",
    era: "1970s",
    pos: "RW",
    stats: { g: 36, a: 61, p: 97, pm: 25 },
    rating: 80,
    notable: "HOF, Mr. Ranger",
  },
  {
    name: "Reggie Leach",
    team: "flyers",
    era: "1970s",
    pos: "RW",
    stats: { g: 61, a: 30, p: 91, pm: 30 },
    rating: 78,
    notable: "Stanley Cup, Conn Smythe, the Riverton Rifle",
  },

  // Defensemen
  {
    name: "Bobby Orr",
    team: "bruins",
    era: "1970s",
    pos: "D",
    stats: { g: 46, a: 89, p: 135, pm: 124 },
    rating: 97,
    notable: "HOF, 2x Stanley Cup, 8x Norris, 3x MVP",
  },
  {
    name: "Brad Park",
    team: "rangers",
    era: "1970s",
    pos: "D",
    stats: { g: 25, a: 57, p: 82, pm: 40 },
    rating: 86,
    notable: "HOF, 6x Norris runner-up",
  },
  {
    name: "Denis Potvin",
    team: "islanders",
    era: "1970s",
    pos: "D",
    stats: { g: 31, a: 70, p: 101, pm: 50 },
    rating: 89,
    notable: "HOF, 4x Stanley Cup, 3x Norris",
  },
  {
    name: "Larry Robinson",
    team: "canadiens",
    era: "1970s",
    pos: "D",
    stats: { g: 19, a: 66, p: 85, pm: 120 },
    rating: 88,
    notable: "HOF, 6x Stanley Cup, 2x Norris",
  },
  {
    name: "Serge Savard",
    team: "canadiens",
    era: "1970s",
    pos: "D",
    stats: { g: 20, a: 40, p: 60, pm: 60 },
    rating: 82,
    notable: "HOF, 8x Stanley Cup champion",
  },
  {
    name: "Guy Lapointe",
    team: "canadiens",
    era: "1970s",
    pos: "D",
    stats: { g: 28, a: 47, p: 75, pm: 70 },
    rating: 81,
    notable: "HOF, 6x Stanley Cup, Big Three",
  },

  // Goalies
  {
    name: "Ken Dryden",
    team: "canadiens",
    era: "1970s",
    pos: "G",
    stats: { w: 42, svp: 0.922, gaa: 2.24, so: 8 },
    rating: 89,
    notable: "HOF, 6x Stanley Cup, 5x Vezina",
  },
  {
    name: "Bernie Parent",
    team: "flyers",
    era: "1970s",
    pos: "G",
    stats: { w: 47, svp: 0.923, gaa: 1.89, so: 12 },
    rating: 88,
    notable: "HOF, 2x Stanley Cup, 2x Vezina, 2x Conn Smythe",
  },
  {
    name: "Tony Esposito",
    team: "blackhawks",
    era: "1970s",
    pos: "G",
    stats: { w: 38, svp: 0.92, gaa: 2.17, so: 15 },
    rating: 86,
    notable: "HOF, 3x Vezina, 15 shutouts as a rookie",
  },
  {
    name: "Gerry Cheevers",
    team: "bruins",
    era: "1970s",
    pos: "G",
    stats: { w: 36, svp: 0.918, gaa: 2.5, so: 6 },
    rating: 82,
    notable: "HOF, 2x Stanley Cup champion",
  },
  {
    name: "Rogie Vachon",
    team: "kings",
    era: "1970s",
    pos: "G",
    stats: { w: 33, svp: 0.917, gaa: 2.6, so: 8 },
    rating: 80,
    notable: "HOF, 3x Stanley Cup, Canada Cup MVP",
  },

  // =========================================================================
  // 1980s — explosive offense. Gretzky/Lemieux peaks are genuinely enormous.
  // =========================================================================

  // Centers
  {
    name: "Wayne Gretzky",
    team: "oilers",
    era: "1980s",
    pos: "C",
    stats: { g: 52, a: 163, p: 215, pm: 98 },
    rating: 99,
    notable: "HOF, 4x Stanley Cup, 9x MVP, 10x Art Ross",
  },
  {
    name: "Mario Lemieux",
    team: "penguins",
    era: "1980s",
    pos: "C",
    stats: { g: 85, a: 114, p: 199, pm: 41 },
    rating: 96,
    notable: "HOF, 2x Stanley Cup, 3x MVP, 6x Art Ross",
  },
  {
    name: "Bryan Trottier",
    team: "islanders",
    era: "1980s",
    pos: "C",
    stats: { g: 50, a: 79, p: 129, pm: 70 },
    rating: 87,
    notable: "HOF, 6x Stanley Cup champion",
  },
  {
    name: "Dale Hawerchuk",
    team: "jets",
    era: "1980s",
    pos: "C",
    stats: { g: 53, a: 77, p: 130, pm: 20 },
    rating: 86,
    notable: "HOF, Calder Trophy, 5x 100-point seasons",
  },
  {
    name: "Denis Savard",
    team: "blackhawks",
    era: "1980s",
    pos: "C",
    stats: { g: 47, a: 87, p: 134, pm: 25 },
    rating: 85,
    notable: "HOF, Stanley Cup, electrifying spin-o-rama",
  },
  {
    name: "Peter Stastny",
    team: "avalanche",
    era: "1980s",
    pos: "C",
    stats: { g: 46, a: 93, p: 139, pm: 30 },
    rating: 85,
    notable: "HOF, Calder, 6x 100-point seasons (Nordiques)",
  },

  // Left Wings
  {
    name: "Michel Goulet",
    team: "avalanche",
    era: "1980s",
    pos: "LW",
    stats: { g: 57, a: 65, p: 122, pm: 30 },
    rating: 84,
    notable: "HOF, 4x 50-goal seasons (Nordiques)",
  },
  {
    name: "Mark Messier",
    team: "oilers",
    era: "1980s",
    pos: "LW",
    stats: { g: 48, a: 63, p: 111, pm: 45 },
    rating: 90,
    notable: "HOF, 5x Stanley Cup, 2x MVP",
  },
  {
    name: "John Tonelli",
    team: "islanders",
    era: "1980s",
    pos: "LW",
    stats: { g: 42, a: 58, p: 100, pm: 40 },
    rating: 79,
    notable: "4x Stanley Cup champion",
  },
  {
    name: "Brian Bellows",
    team: "stars",
    era: "1980s",
    pos: "LW",
    stats: { g: 55, a: 44, p: 99, pm: 15 },
    rating: 78,
    notable: "All-Star, North Stars sniper",
  },

  // Right Wings
  {
    name: "Jari Kurri",
    team: "oilers",
    era: "1980s",
    pos: "RW",
    stats: { g: 71, a: 64, p: 135, pm: 76 },
    rating: 88,
    notable: "HOF, 5x Stanley Cup, Gretzky's winger",
  },
  {
    name: "Mike Bossy",
    team: "islanders",
    era: "1980s",
    pos: "RW",
    stats: { g: 64, a: 83, p: 147, pm: 40 },
    rating: 90,
    notable: "HOF, 4x Stanley Cup, 9x 50-goal seasons",
  },
  {
    name: "Glenn Anderson",
    team: "oilers",
    era: "1980s",
    pos: "RW",
    stats: { g: 54, a: 45, p: 99, pm: 35 },
    rating: 82,
    notable: "HOF, 6x Stanley Cup champion",
  },
  {
    name: "Tim Kerr",
    team: "flyers",
    era: "1980s",
    pos: "RW",
    stats: { g: 58, a: 34, p: 92, pm: 20 },
    rating: 78,
    notable: "4x 50-goal seasons, power-play machine",
  },
  {
    name: "Dino Ciccarelli",
    team: "stars",
    era: "1980s",
    pos: "RW",
    stats: { g: 55, a: 52, p: 107, pm: 18 },
    rating: 80,
    notable: "HOF, 600+ career goals",
  },

  // Defensemen
  {
    name: "Ray Bourque",
    team: "bruins",
    era: "1980s",
    pos: "D",
    stats: { g: 31, a: 65, p: 96, pm: 44 },
    rating: 93,
    notable: "HOF, Stanley Cup, 5x Norris, Calder",
  },
  {
    name: "Paul Coffey",
    team: "oilers",
    era: "1980s",
    pos: "D",
    stats: { g: 48, a: 90, p: 138, pm: 61 },
    rating: 90,
    notable: "HOF, 4x Stanley Cup, 3x Norris",
  },
  {
    name: "Mark Howe",
    team: "flyers",
    era: "1980s",
    pos: "D",
    stats: { g: 24, a: 58, p: 82, pm: 85 },
    rating: 84,
    notable: "HOF, 3x Norris runner-up",
  },
  {
    name: "Rod Langway",
    team: "capitals",
    era: "1980s",
    pos: "D",
    stats: { g: 9, a: 34, p: 43, pm: 50 },
    rating: 83,
    notable: "HOF, 2x Norris, defensive anchor",
  },
  {
    name: "Chris Chelios",
    team: "blackhawks",
    era: "1980s",
    pos: "D",
    stats: { g: 20, a: 64, p: 84, pm: 35 },
    rating: 88,
    notable: "HOF, Stanley Cup, 3x Norris",
  },
  {
    name: "Larry Murphy",
    team: "capitals",
    era: "1980s",
    pos: "D",
    stats: { g: 23, a: 61, p: 84, pm: 40 },
    rating: 81,
    notable: "HOF, 4x Stanley Cup champion",
  },

  // Goalies
  {
    name: "Grant Fuhr",
    team: "oilers",
    era: "1980s",
    pos: "G",
    stats: { w: 40, svp: 0.902, gaa: 3.2, so: 4 },
    rating: 86,
    notable: "HOF, 5x Stanley Cup, Vezina",
  },
  {
    name: "Billy Smith",
    team: "islanders",
    era: "1980s",
    pos: "G",
    stats: { w: 38, svp: 0.901, gaa: 2.97, so: 3 },
    rating: 84,
    notable: "HOF, 4x Stanley Cup, Conn Smythe",
  },
  {
    name: "Mike Liut",
    team: "blues",
    era: "1980s",
    pos: "G",
    stats: { w: 33, svp: 0.9, gaa: 3.2, so: 3 },
    rating: 79,
    notable: "Lester B. Pearson Award",
  },
  {
    name: "Pelle Lindbergh",
    team: "flyers",
    era: "1980s",
    pos: "G",
    stats: { w: 40, svp: 0.899, gaa: 3.02, so: 3 },
    rating: 80,
    notable: "Vezina Trophy winner",
  },
  {
    name: "Tom Barrasso",
    team: "sabres",
    era: "1980s",
    pos: "G",
    stats: { w: 37, svp: 0.903, gaa: 2.84, so: 5 },
    rating: 82,
    notable: "Vezina, Calder, 2x Stanley Cup",
  },

  // =========================================================================
  // 1990s — offense cools mid-decade; Hasek/Roy peak, big stars everywhere.
  // =========================================================================

  // Centers
  {
    name: "Mario Lemieux",
    team: "penguins",
    era: "1990s",
    pos: "C",
    stats: { g: 69, a: 92, p: 161, pm: 55 },
    rating: 96,
    notable: "HOF, 2x Stanley Cup, 6x Art Ross",
  },
  {
    name: "Steve Yzerman",
    team: "redwings",
    era: "1990s",
    pos: "C",
    stats: { g: 65, a: 90, p: 155, pm: 33 },
    rating: 91,
    notable: "HOF, 3x Stanley Cup, Conn Smythe",
  },
  {
    name: "Mark Messier",
    team: "rangers",
    era: "1990s",
    pos: "C",
    stats: { g: 35, a: 72, p: 107, pm: 25 },
    rating: 89,
    notable: "HOF, 6x Stanley Cup, ended Rangers drought",
  },
  {
    name: "Sergei Fedorov",
    team: "redwings",
    era: "1990s",
    pos: "C",
    stats: { g: 56, a: 64, p: 120, pm: 48 },
    rating: 88,
    notable: "HOF, 3x Stanley Cup, MVP, Selke",
  },
  {
    name: "Joe Sakic",
    team: "avalanche",
    era: "1990s",
    pos: "C",
    stats: { g: 51, a: 69, p: 120, pm: 31 },
    rating: 90,
    notable: "HOF, 2x Stanley Cup, Conn Smythe, MVP",
  },
  {
    name: "Eric Lindros",
    team: "flyers",
    era: "1990s",
    pos: "C",
    stats: { g: 47, a: 68, p: 115, pm: 40 },
    rating: 85,
    notable: "HOF, MVP, the Big E",
  },
  {
    name: "Ron Francis",
    team: "hurricanes",
    era: "1990s",
    pos: "C",
    stats: { g: 27, a: 92, p: 119, pm: 30 },
    rating: 84,
    notable: "HOF, 2x Stanley Cup, 5th all-time assists",
  },

  // Left Wings
  {
    name: "Brendan Shanahan",
    team: "redwings",
    era: "1990s",
    pos: "LW",
    stats: { g: 51, a: 51, p: 102, pm: 30 },
    rating: 86,
    notable: "HOF, 3x Stanley Cup, 600+ goals",
  },
  {
    name: "Luc Robitaille",
    team: "kings",
    era: "1990s",
    pos: "LW",
    stats: { g: 63, a: 62, p: 125, pm: 18 },
    rating: 87,
    notable: "HOF, Stanley Cup, most goals by a LW",
  },
  {
    name: "Keith Tkachuk",
    team: "coyotes",
    era: "1990s",
    pos: "LW",
    stats: { g: 52, a: 34, p: 86, pm: 15 },
    rating: 80,
    notable: "500+ goals, power forward",
  },
  {
    name: "John LeClair",
    team: "flyers",
    era: "1990s",
    pos: "LW",
    stats: { g: 51, a: 46, p: 97, pm: 44 },
    rating: 80,
    notable: "3x 50-goal seasons, Legion of Doom",
  },
  {
    name: "Kevin Stevens",
    team: "penguins",
    era: "1990s",
    pos: "LW",
    stats: { g: 55, a: 56, p: 111, pm: 30 },
    rating: 78,
    notable: "2x Stanley Cup, power forward",
  },

  // Right Wings
  {
    name: "Jaromir Jagr",
    team: "penguins",
    era: "1990s",
    pos: "RW",
    stats: { g: 62, a: 87, p: 149, pm: 37 },
    rating: 93,
    notable: "HOF, 2x Stanley Cup, 5x Art Ross, MVP",
  },
  {
    name: "Brett Hull",
    team: "blues",
    era: "1990s",
    pos: "RW",
    stats: { g: 86, a: 45, p: 131, pm: 23 },
    rating: 90,
    notable: "HOF, 2x Stanley Cup, MVP, 741 goals",
  },
  {
    name: "Pavel Bure",
    team: "canucks",
    era: "1990s",
    pos: "RW",
    stats: { g: 60, a: 50, p: 110, pm: 25 },
    rating: 86,
    notable: "HOF, Calder, the Russian Rocket",
  },
  {
    name: "Teemu Selanne",
    team: "ducks",
    era: "1990s",
    pos: "RW",
    stats: { g: 76, a: 56, p: 132, pm: 28 },
    rating: 89,
    notable: "HOF, Stanley Cup, 76-goal rookie record",
  },
  {
    name: "Mark Recchi",
    team: "penguins",
    era: "1990s",
    pos: "RW",
    stats: { g: 53, a: 70, p: 123, pm: 20 },
    rating: 82,
    notable: "HOF, 3x Stanley Cup champion",
  },
  {
    name: "Cam Neely",
    team: "bruins",
    era: "1990s",
    pos: "RW",
    stats: { g: 50, a: 26, p: 76, pm: 20 },
    rating: 82,
    notable: "HOF, prototypical power forward",
  },

  // Defensemen
  {
    name: "Ray Bourque",
    team: "bruins",
    era: "1990s",
    pos: "D",
    stats: { g: 21, a: 73, p: 94, pm: 33 },
    rating: 92,
    notable: "HOF, 5x Norris, all-time D scoring leader",
  },
  {
    name: "Nicklas Lidstrom",
    team: "redwings",
    era: "1990s",
    pos: "D",
    stats: { g: 20, a: 53, p: 73, pm: 40 },
    rating: 92,
    notable: "HOF, 4x Stanley Cup, 7x Norris",
  },
  {
    name: "Scott Stevens",
    team: "devils",
    era: "1990s",
    pos: "D",
    stats: { g: 18, a: 60, p: 78, pm: 53 },
    rating: 89,
    notable: "HOF, 3x Stanley Cup, Conn Smythe",
  },
  {
    name: "Chris Chelios",
    team: "blackhawks",
    era: "1990s",
    pos: "D",
    stats: { g: 16, a: 56, p: 72, pm: 40 },
    rating: 89,
    notable: "HOF, 3x Norris, ironman defenseman",
  },
  {
    name: "Brian Leetch",
    team: "rangers",
    era: "1990s",
    pos: "D",
    stats: { g: 22, a: 80, p: 102, pm: 25 },
    rating: 89,
    notable: "HOF, Stanley Cup, 2x Norris, Conn Smythe",
  },
  {
    name: "Al MacInnis",
    team: "flames",
    era: "1990s",
    pos: "D",
    stats: { g: 28, a: 75, p: 103, pm: 20 },
    rating: 88,
    notable: "HOF, Stanley Cup, Norris, hardest shot",
  },
  {
    name: "Scott Niedermayer",
    team: "devils",
    era: "1990s",
    pos: "D",
    stats: { g: 14, a: 46, p: 60, pm: 30 },
    rating: 88,
    notable: "HOF, 4x Stanley Cup, Norris",
  },

  // Goalies
  {
    name: "Dominik Hasek",
    team: "sabres",
    era: "1990s",
    pos: "G",
    stats: { w: 37, svp: 0.937, gaa: 1.87, so: 13 },
    rating: 94,
    notable: "HOF, 2x MVP, 6x Vezina, the Dominator",
  },
  {
    name: "Patrick Roy",
    team: "avalanche",
    era: "1990s",
    pos: "G",
    stats: { w: 38, svp: 0.93, gaa: 2.32, so: 7 },
    rating: 94,
    notable: "HOF, 4x Stanley Cup, 3x Conn Smythe",
  },
  {
    name: "Martin Brodeur",
    team: "devils",
    era: "1990s",
    pos: "G",
    stats: { w: 43, svp: 0.927, gaa: 1.88, so: 10 },
    rating: 93,
    notable: "HOF, 3x Stanley Cup, all-time wins leader",
  },
  {
    name: "Ed Belfour",
    team: "blackhawks",
    era: "1990s",
    pos: "G",
    stats: { w: 41, svp: 0.928, gaa: 1.88, so: 7 },
    rating: 88,
    notable: "HOF, Stanley Cup, 2x Vezina, Calder",
  },
  {
    name: "Mike Vernon",
    team: "redwings",
    era: "1990s",
    pos: "G",
    stats: { w: 38, svp: 0.918, gaa: 2.43, so: 4 },
    rating: 82,
    notable: "2x Stanley Cup, Conn Smythe",
  },
  {
    name: "Curtis Joseph",
    team: "mapleleafs",
    era: "1990s",
    pos: "G",
    stats: { w: 39, svp: 0.915, gaa: 2.51, so: 5 },
    rating: 82,
    notable: "454 career wins, CuJo",
  },

  // =========================================================================
  // 2000s — dead puck era. Totals suppressed; ~40g/100p is elite.
  // =========================================================================

  // Centers
  {
    name: "Joe Thornton",
    team: "sharks",
    era: "2000s",
    pos: "C",
    stats: { g: 29, a: 96, p: 125, pm: 25 },
    rating: 88,
    notable: "HOF-bound, MVP, Art Ross, 1000+ assists",
  },
  {
    name: "Sidney Crosby",
    team: "penguins",
    era: "2000s",
    pos: "C",
    stats: { g: 51, a: 69, p: 120, pm: 30 },
    rating: 93,
    notable: "3x Stanley Cup, 2x MVP, 2x Conn Smythe",
  },
  {
    name: "Joe Sakic",
    team: "avalanche",
    era: "2000s",
    pos: "C",
    stats: { g: 50, a: 50, p: 100, pm: 24 },
    rating: 89,
    notable: "HOF, Stanley Cup, MVP",
  },
  {
    name: "Pavel Datsyuk",
    team: "redwings",
    era: "2000s",
    pos: "C",
    stats: { g: 31, a: 66, p: 97, pm: 41 },
    rating: 89,
    notable: "HOF, 2x Stanley Cup, 4x Selke, Magic Man",
  },
  {
    name: "Vincent Lecavalier",
    team: "lightning",
    era: "2000s",
    pos: "C",
    stats: { g: 52, a: 56, p: 108, pm: 2 },
    rating: 83,
    notable: "Stanley Cup, Rocket Richard",
  },
  {
    name: "Evgeni Malkin",
    team: "penguins",
    era: "2000s",
    pos: "C",
    stats: { g: 35, a: 78, p: 113, pm: 18 },
    rating: 89,
    notable: "3x Stanley Cup, MVP, 2x Art Ross, Conn Smythe",
  },

  // Left Wings
  {
    name: "Alex Ovechkin",
    team: "capitals",
    era: "2000s",
    pos: "LW",
    stats: { g: 65, a: 47, p: 112, pm: 28 },
    rating: 94,
    notable: "Stanley Cup, 3x MVP, all-time goals leader",
  },
  {
    name: "Marian Hossa",
    team: "blackhawks",
    era: "2000s",
    pos: "LW",
    stats: { g: 45, a: 55, p: 100, pm: 25 },
    rating: 85,
    notable: "HOF, 3x Stanley Cup, two-way star",
  },
  {
    name: "Daniel Sedin",
    team: "canucks",
    era: "2000s",
    pos: "LW",
    stats: { g: 41, a: 63, p: 104, pm: 30 },
    rating: 84,
    notable: "HOF, Art Ross, MVP",
  },
  {
    name: "Ilya Kovalchuk",
    team: "jets",
    era: "2000s",
    pos: "LW",
    stats: { g: 52, a: 46, p: 98, pm: -8 },
    rating: 82,
    notable: "Rocket Richard, elite sniper (Atlanta)",
  },
  {
    name: "Patrick Marleau",
    team: "sharks",
    era: "2000s",
    pos: "LW",
    stats: { g: 44, a: 42, p: 86, pm: 23 },
    rating: 80,
    notable: "NHL games-played record holder",
  },

  // Right Wings
  {
    name: "Jaromir Jagr",
    team: "penguins",
    era: "2000s",
    pos: "RW",
    stats: { g: 52, a: 69, p: 121, pm: 24 },
    rating: 90,
    notable: "HOF, Art Ross, 2nd all-time points",
  },
  {
    name: "Jarome Iginla",
    team: "flames",
    era: "2000s",
    pos: "RW",
    stats: { g: 52, a: 44, p: 96, pm: 27 },
    rating: 87,
    notable: "HOF, 2x Rocket Richard, Art Ross, 600+ goals",
  },
  {
    name: "Marian Gaborik",
    team: "wild",
    era: "2000s",
    pos: "RW",
    stats: { g: 42, a: 41, p: 83, pm: 20 },
    rating: 80,
    notable: "Rocket Richard, elite speed",
  },
  {
    name: "Daniel Alfredsson",
    team: "senators",
    era: "2000s",
    pos: "RW",
    stats: { g: 43, a: 60, p: 103, pm: 42 },
    rating: 84,
    notable: "HOF, Calder, Senators captain",
  },
  {
    name: "Teemu Selanne",
    team: "ducks",
    era: "2000s",
    pos: "RW",
    stats: { g: 48, a: 46, p: 94, pm: 28 },
    rating: 85,
    notable: "HOF, Stanley Cup, Finnish Flash",
  },

  // Defensemen
  {
    name: "Nicklas Lidstrom",
    team: "redwings",
    era: "2000s",
    pos: "D",
    stats: { g: 16, a: 64, p: 80, pm: 40 },
    rating: 94,
    notable: "HOF, 4x Stanley Cup, 7x Norris, Conn Smythe",
  },
  {
    name: "Chris Pronger",
    team: "blues",
    era: "2000s",
    pos: "D",
    stats: { g: 14, a: 48, p: 62, pm: 52 },
    rating: 89,
    notable: "HOF, Stanley Cup, Norris, MVP",
  },
  {
    name: "Scott Niedermayer",
    team: "ducks",
    era: "2000s",
    pos: "D",
    stats: { g: 15, a: 54, p: 69, pm: 30 },
    rating: 88,
    notable: "HOF, 4x Stanley Cup, Norris, Conn Smythe",
  },
  {
    name: "Zdeno Chara",
    team: "bruins",
    era: "2000s",
    pos: "D",
    stats: { g: 19, a: 33, p: 52, pm: 35 },
    rating: 86,
    notable: "HOF-bound, Stanley Cup, Norris, hardest shot",
  },
  {
    name: "Sergei Gonchar",
    team: "penguins",
    era: "2000s",
    pos: "D",
    stats: { g: 18, a: 49, p: 67, pm: 13 },
    rating: 82,
    notable: "Stanley Cup, elite power-play QB",
  },
  {
    name: "Dan Boyle",
    team: "sharks",
    era: "2000s",
    pos: "D",
    stats: { g: 16, a: 41, p: 57, pm: 20 },
    rating: 79,
    notable: "Stanley Cup, offensive defenseman",
  },

  // Goalies
  {
    name: "Martin Brodeur",
    team: "devils",
    era: "2000s",
    pos: "G",
    stats: { w: 48, svp: 0.929, gaa: 2.02, so: 12 },
    rating: 93,
    notable: "HOF, 3x Stanley Cup, 4x Vezina, record 691 wins",
  },
  {
    name: "Roberto Luongo",
    team: "canucks",
    era: "2000s",
    pos: "G",
    stats: { w: 47, svp: 0.928, gaa: 2.11, so: 9 },
    rating: 87,
    notable: "HOF, 2x Olympic gold, 489 career wins",
  },
  {
    name: "Henrik Lundqvist",
    team: "rangers",
    era: "2000s",
    pos: "G",
    stats: { w: 38, svp: 0.926, gaa: 2.23, so: 8 },
    rating: 88,
    notable: "HOF, Vezina, King Henrik",
  },
  {
    name: "Miikka Kiprusoff",
    team: "flames",
    era: "2000s",
    pos: "G",
    stats: { w: 42, svp: 0.923, gaa: 2.07, so: 10 },
    rating: 83,
    notable: "Vezina, Jennings",
  },
  {
    name: "Evgeni Nabokov",
    team: "sharks",
    era: "2000s",
    pos: "G",
    stats: { w: 46, svp: 0.918, gaa: 2.44, so: 9 },
    rating: 81,
    notable: "Calder Trophy, Sharks all-time wins",
  },
  {
    name: "Marc-Andre Fleury",
    team: "penguins",
    era: "2000s",
    pos: "G",
    stats: { w: 40, svp: 0.921, gaa: 2.33, so: 4 },
    rating: 85,
    notable: "3x Stanley Cup, Vezina, 2nd all-time wins",
  },

  // =========================================================================
  // 2010s — moderate scoring. McDavid/Crosby/Ovechkin headline.
  // =========================================================================

  // Centers
  {
    name: "Connor McDavid",
    team: "oilers",
    era: "2010s",
    pos: "C",
    stats: { g: 41, a: 67, p: 108, pm: 28 },
    rating: 95,
    notable: "3x MVP, 4x Art Ross, fastest player alive",
  },
  {
    name: "Sidney Crosby",
    team: "penguins",
    era: "2010s",
    pos: "C",
    stats: { g: 44, a: 60, p: 104, pm: 18 },
    rating: 94,
    notable: "3x Stanley Cup, MVP, 2x Conn Smythe",
  },
  {
    name: "Evgeni Malkin",
    team: "penguins",
    era: "2010s",
    pos: "C",
    stats: { g: 49, a: 60, p: 109, pm: 18 },
    rating: 89,
    notable: "Art Ross, MVP, 3x Stanley Cup",
  },
  {
    name: "Nathan MacKinnon",
    team: "avalanche",
    era: "2010s",
    pos: "C",
    stats: { g: 41, a: 58, p: 99, pm: 20 },
    rating: 90,
    notable: "Calder, Stanley Cup, elite speed",
  },
  {
    name: "Steven Stamkos",
    team: "lightning",
    era: "2010s",
    pos: "C",
    stats: { g: 60, a: 37, p: 97, pm: 25 },
    rating: 87,
    notable: "2x Stanley Cup, 2x Rocket Richard",
  },
  {
    name: "Anze Kopitar",
    team: "kings",
    era: "2010s",
    pos: "C",
    stats: { g: 28, a: 64, p: 92, pm: 34 },
    rating: 86,
    notable: "2x Stanley Cup, 2x Selke",
  },
  {
    name: "John Tavares",
    team: "islanders",
    era: "2010s",
    pos: "C",
    stats: { g: 38, a: 48, p: 86, pm: 10 },
    rating: 84,
    notable: "All-Star, Islanders captain",
  },

  // Left Wings
  {
    name: "Alex Ovechkin",
    team: "capitals",
    era: "2010s",
    pos: "LW",
    stats: { g: 53, a: 34, p: 87, pm: 12 },
    rating: 93,
    notable: "Stanley Cup, MVP, 9x Rocket Richard",
  },
  {
    name: "Jamie Benn",
    team: "stars",
    era: "2010s",
    pos: "LW",
    stats: { g: 35, a: 54, p: 89, pm: 20 },
    rating: 83,
    notable: "Art Ross, Stars captain",
  },
  {
    name: "Taylor Hall",
    team: "devils",
    era: "2010s",
    pos: "LW",
    stats: { g: 39, a: 54, p: 93, pm: 8 },
    rating: 81,
    notable: "Hart Trophy MVP",
  },
  {
    name: "Johnny Gaudreau",
    team: "flames",
    era: "2010s",
    pos: "LW",
    stats: { g: 40, a: 75, p: 115, pm: 64 },
    rating: 83,
    notable: "All-Star, Johnny Hockey",
  },
  {
    name: "Gabriel Landeskog",
    team: "avalanche",
    era: "2010s",
    pos: "LW",
    stats: { g: 34, a: 41, p: 75, pm: 20 },
    rating: 80,
    notable: "Stanley Cup, Avalanche captain",
  },

  // Right Wings
  {
    name: "Patrick Kane",
    team: "blackhawks",
    era: "2010s",
    pos: "RW",
    stats: { g: 46, a: 64, p: 110, pm: 17 },
    rating: 90,
    notable: "3x Stanley Cup, MVP, Art Ross, Conn Smythe",
  },
  {
    name: "Nikita Kucherov",
    team: "lightning",
    era: "2010s",
    pos: "RW",
    stats: { g: 41, a: 87, p: 128, pm: 24 },
    rating: 90,
    notable: "2x Stanley Cup, MVP, Art Ross",
  },
  {
    name: "Phil Kessel",
    team: "penguins",
    era: "2010s",
    pos: "RW",
    stats: { g: 37, a: 55, p: 92, pm: 8 },
    rating: 82,
    notable: "2x Stanley Cup, ironman streak",
  },
  {
    name: "Vladimir Tarasenko",
    team: "blues",
    era: "2010s",
    pos: "RW",
    stats: { g: 40, a: 35, p: 75, pm: 20 },
    rating: 82,
    notable: "Stanley Cup, elite sniper",
  },
  {
    name: "Blake Wheeler",
    team: "jets",
    era: "2010s",
    pos: "RW",
    stats: { g: 28, a: 63, p: 91, pm: 15 },
    rating: 79,
    notable: "All-Star, Jets captain",
  },

  // Defensemen
  {
    name: "Erik Karlsson",
    team: "senators",
    era: "2010s",
    pos: "D",
    stats: { g: 21, a: 61, p: 82, pm: 20 },
    rating: 89,
    notable: "2x Norris, elite offensive defenseman",
  },
  {
    name: "Drew Doughty",
    team: "kings",
    era: "2010s",
    pos: "D",
    stats: { g: 16, a: 44, p: 60, pm: 35 },
    rating: 88,
    notable: "2x Stanley Cup, Norris",
  },
  {
    name: "Duncan Keith",
    team: "blackhawks",
    era: "2010s",
    pos: "D",
    stats: { g: 12, a: 49, p: 61, pm: 30 },
    rating: 87,
    notable: "3x Stanley Cup, 2x Norris, Conn Smythe",
  },
  {
    name: "P.K. Subban",
    team: "canadiens",
    era: "2010s",
    pos: "D",
    stats: { g: 15, a: 45, p: 60, pm: 25 },
    rating: 84,
    notable: "Norris Trophy, electric talent",
  },
  {
    name: "Victor Hedman",
    team: "lightning",
    era: "2010s",
    pos: "D",
    stats: { g: 17, a: 63, p: 80, pm: 30 },
    rating: 88,
    notable: "2x Stanley Cup, Norris, Conn Smythe",
  },
  {
    name: "Shea Weber",
    team: "predators",
    era: "2010s",
    pos: "D",
    stats: { g: 23, a: 33, p: 56, pm: 20 },
    rating: 85,
    notable: "Predators captain, thunderous shot",
  },
  {
    name: "Brent Burns",
    team: "sharks",
    era: "2010s",
    pos: "D",
    stats: { g: 29, a: 47, p: 76, pm: 20 },
    rating: 84,
    notable: "Norris Trophy, iconic beard",
  },

  // Goalies
  {
    name: "Carey Price",
    team: "canadiens",
    era: "2010s",
    pos: "G",
    stats: { w: 44, svp: 0.933, gaa: 1.96, so: 9 },
    rating: 88,
    notable: "MVP, Vezina, Olympic gold",
  },
  {
    name: "Andrei Vasilevskiy",
    team: "lightning",
    era: "2010s",
    pos: "G",
    stats: { w: 39, svp: 0.925, gaa: 2.4, so: 6 },
    rating: 90,
    notable: "2x Stanley Cup, Vezina, Conn Smythe",
  },
  {
    name: "Braden Holtby",
    team: "capitals",
    era: "2010s",
    pos: "G",
    stats: { w: 48, svp: 0.925, gaa: 2.2, so: 9 },
    rating: 84,
    notable: "Stanley Cup, Vezina",
  },
  {
    name: "Sergei Bobrovsky",
    team: "bluejackets",
    era: "2010s",
    pos: "G",
    stats: { w: 41, svp: 0.932, gaa: 2.06, so: 9 },
    rating: 85,
    notable: "2x Vezina Trophy",
  },
  {
    name: "Jonathan Quick",
    team: "kings",
    era: "2010s",
    pos: "G",
    stats: { w: 35, svp: 0.929, gaa: 1.95, so: 10 },
    rating: 84,
    notable: "2x Stanley Cup, Conn Smythe",
  },
  {
    name: "Pekka Rinne",
    team: "predators",
    era: "2010s",
    pos: "G",
    stats: { w: 43, svp: 0.927, gaa: 2.18, so: 8 },
    rating: 83,
    notable: "Vezina, Predators legend",
  },

  // =========================================================================
  // 2020s — current stars at their peak.
  // =========================================================================

  // Centers
  {
    name: "Connor McDavid",
    team: "oilers",
    era: "2020s",
    pos: "C",
    stats: { g: 64, a: 89, p: 153, pm: 22 },
    rating: 97,
    notable: "3x MVP, 5x Art Ross, generational talent",
  },
  {
    name: "Nathan MacKinnon",
    team: "avalanche",
    era: "2020s",
    pos: "C",
    stats: { g: 51, a: 89, p: 140, pm: 35 },
    rating: 93,
    notable: "Stanley Cup, MVP runner-up, Conn Smythe",
  },
  {
    name: "Auston Matthews",
    team: "mapleleafs",
    era: "2020s",
    pos: "C",
    stats: { g: 69, a: 38, p: 107, pm: 30 },
    rating: 91,
    notable: "MVP, 3x Rocket Richard, 60-goal scorer",
  },
  {
    name: "Sidney Crosby",
    team: "penguins",
    era: "2020s",
    pos: "C",
    stats: { g: 35, a: 59, p: 94, pm: 18 },
    rating: 90,
    notable: "3x Stanley Cup, ageless captain",
  },
  {
    name: "Jack Eichel",
    team: "goldenknights",
    era: "2020s",
    pos: "C",
    stats: { g: 28, a: 66, p: 94, pm: 30 },
    rating: 86,
    notable: "Stanley Cup champion",
  },

  // Left Wings
  {
    name: "Kirill Kaprizov",
    team: "wild",
    era: "2020s",
    pos: "LW",
    stats: { g: 47, a: 49, p: 96, pm: 12 },
    rating: 88,
    notable: "Calder, Wild franchise star",
  },
  {
    name: "Artemi Panarin",
    team: "rangers",
    era: "2020s",
    pos: "LW",
    stats: { g: 49, a: 71, p: 120, pm: 18 },
    rating: 89,
    notable: "All-Star, the Breadman",
  },
  {
    name: "Matthew Tkachuk",
    team: "panthers",
    era: "2020s",
    pos: "LW",
    stats: { g: 40, a: 69, p: 109, pm: 30 },
    rating: 88,
    notable: "Stanley Cup, power forward",
  },
  {
    name: "Brad Marchand",
    team: "bruins",
    era: "2020s",
    pos: "LW",
    stats: { g: 32, a: 48, p: 80, pm: 25 },
    rating: 85,
    notable: "Stanley Cup, agitator and scorer",
  },
  {
    name: "Alex Ovechkin",
    team: "capitals",
    era: "2020s",
    pos: "LW",
    stats: { g: 50, a: 40, p: 90, pm: 10 },
    rating: 90,
    notable: "All-time goals leader, passed Gretzky",
  },

  // Right Wings
  {
    name: "Nikita Kucherov",
    team: "lightning",
    era: "2020s",
    pos: "RW",
    stats: { g: 44, a: 100, p: 144, pm: 20 },
    rating: 92,
    notable: "2x Stanley Cup, MVP, 2x Art Ross",
  },
  {
    name: "David Pastrnak",
    team: "bruins",
    era: "2020s",
    pos: "RW",
    stats: { g: 61, a: 52, p: 113, pm: 25 },
    rating: 90,
    notable: "Rocket Richard, Bruins sniper",
  },
  {
    name: "Mitch Marner",
    team: "mapleleafs",
    era: "2020s",
    pos: "RW",
    stats: { g: 35, a: 64, p: 99, pm: 25 },
    rating: 86,
    notable: "All-Star, elite playmaker",
  },
  {
    name: "Mikko Rantanen",
    team: "avalanche",
    era: "2020s",
    pos: "RW",
    stats: { g: 55, a: 50, p: 105, pm: 30 },
    rating: 88,
    notable: "Stanley Cup, elite winger",
  },
  {
    name: "Mark Stone",
    team: "goldenknights",
    era: "2020s",
    pos: "RW",
    stats: { g: 24, a: 40, p: 64, pm: 30 },
    rating: 83,
    notable: "Stanley Cup, Golden Knights captain",
  },

  // Defensemen
  {
    name: "Cale Makar",
    team: "avalanche",
    era: "2020s",
    pos: "D",
    stats: { g: 28, a: 62, p: 90, pm: 48 },
    rating: 93,
    notable: "Stanley Cup, Norris, Conn Smythe, Calder",
  },
  {
    name: "Roman Josi",
    team: "predators",
    era: "2020s",
    pos: "D",
    stats: { g: 23, a: 73, p: 96, pm: 25 },
    rating: 89,
    notable: "Norris Trophy, Predators captain",
  },
  {
    name: "Victor Hedman",
    team: "lightning",
    era: "2020s",
    pos: "D",
    stats: { g: 20, a: 60, p: 80, pm: 25 },
    rating: 88,
    notable: "2x Stanley Cup, Norris",
  },
  {
    name: "Quinn Hughes",
    team: "canucks",
    era: "2020s",
    pos: "D",
    stats: { g: 17, a: 75, p: 92, pm: 38 },
    rating: 88,
    notable: "Norris Trophy, Canucks captain",
  },
  {
    name: "Adam Fox",
    team: "rangers",
    era: "2020s",
    pos: "D",
    stats: { g: 11, a: 63, p: 74, pm: 30 },
    rating: 86,
    notable: "Norris Trophy, elite puck-mover",
  },
  {
    name: "Charlie McAvoy",
    team: "bruins",
    era: "2020s",
    pos: "D",
    stats: { g: 16, a: 40, p: 56, pm: 45 },
    rating: 83,
    notable: "All-Star, Bruins anchor",
  },

  // Goalies
  {
    name: "Andrei Vasilevskiy",
    team: "lightning",
    era: "2020s",
    pos: "G",
    stats: { w: 39, svp: 0.921, gaa: 2.49, so: 6 },
    rating: 91,
    notable: "2x Stanley Cup, Vezina, Conn Smythe",
  },
  {
    name: "Connor Hellebuyck",
    team: "jets",
    era: "2020s",
    pos: "G",
    stats: { w: 47, svp: 0.925, gaa: 2.39, so: 8 },
    rating: 90,
    notable: "2x Vezina, MVP-caliber goalie",
  },
  {
    name: "Igor Shesterkin",
    team: "rangers",
    era: "2020s",
    pos: "G",
    stats: { w: 36, svp: 0.935, gaa: 2.07, so: 6 },
    rating: 89,
    notable: "Vezina Trophy, Rangers backbone",
  },
  {
    name: "Sergei Bobrovsky",
    team: "panthers",
    era: "2020s",
    pos: "G",
    stats: { w: 42, svp: 0.915, gaa: 2.4, so: 5 },
    rating: 85,
    notable: "Stanley Cup champion",
  },
  {
    name: "Jake Oettinger",
    team: "stars",
    era: "2020s",
    pos: "G",
    stats: { w: 37, svp: 0.919, gaa: 2.4, so: 5 },
    rating: 83,
    notable: "All-Star, Stars franchise goalie",
  },
  {
    name: "Ilya Sorokin",
    team: "islanders",
    era: "2020s",
    pos: "G",
    stats: { w: 31, svp: 0.924, gaa: 2.34, so: 6 },
    rating: 84,
    notable: "All-Star, elite Islanders netminder",
  },
];
