// Generated by scripts/etl/mlb.ts — do not edit by hand.
import type { FranchiseDef } from "@/engine/types";

export const MLB_FRANCHISES: FranchiseDef[] = [
  {
    "id": "angels",
    "name": "Los Angeles Angels",
    "abbr": "LAA",
    "colors": [
      "#BA0021",
      "#003263"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "California Angels"
      },
      {
        "era": "1970s",
        "name": "California Angels"
      },
      {
        "era": "1980s",
        "name": "California Angels"
      },
      {
        "era": "1990s",
        "name": "Anaheim Angels"
      },
      {
        "era": "2000s",
        "name": "Los Angeles Angels of Anaheim"
      },
      {
        "era": "2010s",
        "name": "Los Angeles Angels of Anaheim"
      },
      {
        "era": "2020s",
        "name": "Los Angeles Angels of Anaheim"
      }
    ]
  },
  {
    "id": "diamondbacks",
    "name": "Arizona Diamondbacks",
    "abbr": "ARI",
    "colors": [
      "#A71930",
      "#E3D4AD"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "braves",
    "name": "Atlanta Braves",
    "abbr": "ATL",
    "colors": [
      "#CE1141",
      "#13274F"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1910s",
        "name": "Boston Braves"
      },
      {
        "era": "1920s",
        "name": "Boston Braves"
      },
      {
        "era": "1930s",
        "name": "Boston Bees"
      },
      {
        "era": "1940s",
        "name": "Boston Braves"
      },
      {
        "era": "1950s",
        "name": "Milwaukee Braves"
      }
    ]
  },
  {
    "id": "orioles",
    "name": "Baltimore Orioles",
    "abbr": "BAL",
    "colors": [
      "#DF4601",
      "#000000"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1910s",
        "name": "St. Louis Browns"
      },
      {
        "era": "1920s",
        "name": "St. Louis Browns"
      },
      {
        "era": "1930s",
        "name": "St. Louis Browns"
      },
      {
        "era": "1940s",
        "name": "St. Louis Browns"
      }
    ]
  },
  {
    "id": "redsox",
    "name": "Boston Red Sox",
    "abbr": "BOS",
    "colors": [
      "#BD3039",
      "#0C2340"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "cubs",
    "name": "Chicago Cubs",
    "abbr": "CHC",
    "colors": [
      "#0E3386",
      "#CC3433"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "whitesox",
    "name": "Chicago White Sox",
    "abbr": "CHW",
    "colors": [
      "#27251F",
      "#C4CED4"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "reds",
    "name": "Cincinnati Reds",
    "abbr": "CIN",
    "colors": [
      "#C6011F",
      "#000000"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1950s",
        "name": "Cincinnati Redlegs"
      }
    ]
  },
  {
    "id": "guardians",
    "name": "Cleveland Guardians",
    "abbr": "CLE",
    "colors": [
      "#00385D",
      "#E50022"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1910s",
        "name": "Cleveland Indians"
      },
      {
        "era": "1920s",
        "name": "Cleveland Indians"
      },
      {
        "era": "1930s",
        "name": "Cleveland Indians"
      },
      {
        "era": "1940s",
        "name": "Cleveland Indians"
      },
      {
        "era": "1950s",
        "name": "Cleveland Indians"
      },
      {
        "era": "1960s",
        "name": "Cleveland Indians"
      },
      {
        "era": "1970s",
        "name": "Cleveland Indians"
      },
      {
        "era": "1980s",
        "name": "Cleveland Indians"
      },
      {
        "era": "1990s",
        "name": "Cleveland Indians"
      },
      {
        "era": "2000s",
        "name": "Cleveland Indians"
      },
      {
        "era": "2010s",
        "name": "Cleveland Indians"
      },
      {
        "era": "2020s",
        "name": "Cleveland Indians"
      }
    ]
  },
  {
    "id": "rockies",
    "name": "Colorado Rockies",
    "abbr": "COL",
    "colors": [
      "#333366",
      "#C4CED4"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "tigers",
    "name": "Detroit Tigers",
    "abbr": "DET",
    "colors": [
      "#0C2340",
      "#FA4616"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "marlins",
    "name": "Miami Marlins",
    "abbr": "MIA",
    "colors": [
      "#00A3E0",
      "#EF3340"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1990s",
        "name": "Florida Marlins"
      },
      {
        "era": "2000s",
        "name": "Florida Marlins"
      }
    ]
  },
  {
    "id": "astros",
    "name": "Houston Astros",
    "abbr": "HOU",
    "colors": [
      "#002D62",
      "#EB6E1F"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "royals",
    "name": "Kansas City Royals",
    "abbr": "KC",
    "colors": [
      "#004687",
      "#BD9B60"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "dodgers",
    "name": "Los Angeles Dodgers",
    "abbr": "LAD",
    "colors": [
      "#005A9C",
      "#EF3E42"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1910s",
        "name": "Brooklyn Robins"
      },
      {
        "era": "1920s",
        "name": "Brooklyn Robins"
      },
      {
        "era": "1930s",
        "name": "Brooklyn Dodgers"
      },
      {
        "era": "1940s",
        "name": "Brooklyn Dodgers"
      }
    ]
  },
  {
    "id": "brewers",
    "name": "Milwaukee Brewers",
    "abbr": "MIL",
    "colors": [
      "#12284B",
      "#FFC52F"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "Seattle Pilots"
      }
    ]
  },
  {
    "id": "twins",
    "name": "Minnesota Twins",
    "abbr": "MIN",
    "colors": [
      "#002B5C",
      "#D31145"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1910s",
        "name": "Washington Senators"
      },
      {
        "era": "1920s",
        "name": "Washington Senators"
      },
      {
        "era": "1930s",
        "name": "Washington Senators"
      },
      {
        "era": "1940s",
        "name": "Washington Senators"
      },
      {
        "era": "1950s",
        "name": "Washington Senators"
      }
    ]
  },
  {
    "id": "mets",
    "name": "New York Mets",
    "abbr": "NYM",
    "colors": [
      "#002D72",
      "#FF5910"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "yankees",
    "name": "New York Yankees",
    "abbr": "NYY",
    "colors": [
      "#003087",
      "#E4002C"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "athletics",
    "name": "Oakland Athletics",
    "abbr": "OAK",
    "colors": [
      "#003831",
      "#EFB21E"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1910s",
        "name": "Philadelphia Athletics"
      },
      {
        "era": "1920s",
        "name": "Philadelphia Athletics"
      },
      {
        "era": "1930s",
        "name": "Philadelphia Athletics"
      },
      {
        "era": "1940s",
        "name": "Philadelphia Athletics"
      },
      {
        "era": "1950s",
        "name": "Kansas City Athletics"
      }
    ]
  },
  {
    "id": "phillies",
    "name": "Philadelphia Phillies",
    "abbr": "PHI",
    "colors": [
      "#E81828",
      "#002D72"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "pirates",
    "name": "Pittsburgh Pirates",
    "abbr": "PIT",
    "colors": [
      "#27251F",
      "#FDB827"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "padres",
    "name": "San Diego Padres",
    "abbr": "SD",
    "colors": [
      "#2F241D",
      "#FFC425"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "mariners",
    "name": "Seattle Mariners",
    "abbr": "SEA",
    "colors": [
      "#0C2C56",
      "#005C5C"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "giants",
    "name": "San Francisco Giants",
    "abbr": "SF",
    "colors": [
      "#FD5A1E",
      "#27251F"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1910s",
        "name": "New York Giants"
      },
      {
        "era": "1920s",
        "name": "New York Giants"
      },
      {
        "era": "1930s",
        "name": "New York Giants"
      },
      {
        "era": "1940s",
        "name": "New York Giants"
      }
    ]
  },
  {
    "id": "cardinals",
    "name": "St. Louis Cardinals",
    "abbr": "STL",
    "colors": [
      "#C41E3A",
      "#0C2340"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "rays",
    "name": "Tampa Bay Rays",
    "abbr": "TB",
    "colors": [
      "#092C5C",
      "#8FBCE6"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1990s",
        "name": "Tampa Bay Devil Rays"
      }
    ]
  },
  {
    "id": "rangers",
    "name": "Texas Rangers",
    "abbr": "TEX",
    "colors": [
      "#003278",
      "#C0111F"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "Washington Senators"
      }
    ]
  },
  {
    "id": "bluejays",
    "name": "Toronto Blue Jays",
    "abbr": "TOR",
    "colors": [
      "#134A8E",
      "#1D2D5C"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "nationals",
    "name": "Washington Nationals",
    "abbr": "WSN",
    "colors": [
      "#AB0003",
      "#14225A"
    ],
    "activeEras": [
      "1910s",
      "1920s",
      "1930s",
      "1940s",
      "1950s",
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "Montreal Expos"
      },
      {
        "era": "1970s",
        "name": "Montreal Expos"
      },
      {
        "era": "1980s",
        "name": "Montreal Expos"
      },
      {
        "era": "1990s",
        "name": "Montreal Expos"
      }
    ]
  }
];
