// Generated by scripts/etl/nfl.ts — do not edit by hand.
import type { FranchiseDef } from "@/engine/types";

export const NFL_FRANCHISES: FranchiseDef[] = [
  {
    "id": "cardinals",
    "name": "Arizona Cardinals",
    "abbr": "ARI",
    "colors": [
      "#97233F",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "St. Louis Cardinals"
      },
      {
        "era": "1970s",
        "name": "St. Louis Cardinals"
      },
      {
        "era": "1980s",
        "name": "St. Louis Cardinals"
      }
    ]
  },
  {
    "id": "falcons",
    "name": "Atlanta Falcons",
    "abbr": "ATL",
    "colors": [
      "#A71930",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "ravens",
    "name": "Baltimore Ravens",
    "abbr": "BAL",
    "colors": [
      "#241773",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "bills",
    "name": "Buffalo Bills",
    "abbr": "BUF",
    "colors": [
      "#00338D",
      "#C60C30"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "panthers",
    "name": "Carolina Panthers",
    "abbr": "CAR",
    "colors": [
      "#0085CA",
      "#101820"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "bears",
    "name": "Chicago Bears",
    "abbr": "CHI",
    "colors": [
      "#0B162A",
      "#C83803"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "bengals",
    "name": "Cincinnati Bengals",
    "abbr": "CIN",
    "colors": [
      "#FB4F14",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "browns",
    "name": "Cleveland Browns",
    "abbr": "CLE",
    "colors": [
      "#311D00",
      "#FF3C00"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "cowboys",
    "name": "Dallas Cowboys",
    "abbr": "DAL",
    "colors": [
      "#003594",
      "#869397"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "broncos",
    "name": "Denver Broncos",
    "abbr": "DEN",
    "colors": [
      "#FB4F14",
      "#002244"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "lions",
    "name": "Detroit Lions",
    "abbr": "DET",
    "colors": [
      "#0076B6",
      "#B0B7BC"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "packers",
    "name": "Green Bay Packers",
    "abbr": "GB",
    "colors": [
      "#203731",
      "#FFB612"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "texans",
    "name": "Houston Texans",
    "abbr": "HOU",
    "colors": [
      "#03202F",
      "#A71930"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "colts",
    "name": "Indianapolis Colts",
    "abbr": "IND",
    "colors": [
      "#002C5F",
      "#A2AAAD"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "Baltimore Colts"
      },
      {
        "era": "1970s",
        "name": "Baltimore Colts"
      },
      {
        "era": "1980s",
        "name": "Baltimore Colts"
      }
    ]
  },
  {
    "id": "jaguars",
    "name": "Jacksonville Jaguars",
    "abbr": "JAX",
    "colors": [
      "#101820",
      "#D7A22A"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "chiefs",
    "name": "Kansas City Chiefs",
    "abbr": "KC",
    "colors": [
      "#E31837",
      "#FFB81C"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "raiders",
    "name": "Las Vegas Raiders",
    "abbr": "LV",
    "colors": [
      "#000000",
      "#A5ACAF"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "Oakland Raiders"
      },
      {
        "era": "1970s",
        "name": "Oakland Raiders"
      },
      {
        "era": "1980s",
        "name": "Los Angeles Raiders"
      },
      {
        "era": "1990s",
        "name": "Oakland Raiders"
      },
      {
        "era": "2000s",
        "name": "Oakland Raiders"
      },
      {
        "era": "2010s",
        "name": "Oakland Raiders"
      }
    ]
  },
  {
    "id": "chargers",
    "name": "Los Angeles Chargers",
    "abbr": "LAC",
    "colors": [
      "#0080C6",
      "#FFC20E"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "San Diego Chargers"
      },
      {
        "era": "1970s",
        "name": "San Diego Chargers"
      },
      {
        "era": "1980s",
        "name": "San Diego Chargers"
      },
      {
        "era": "1990s",
        "name": "San Diego Chargers"
      },
      {
        "era": "2000s",
        "name": "San Diego Chargers"
      },
      {
        "era": "2010s",
        "name": "San Diego Chargers"
      }
    ]
  },
  {
    "id": "rams",
    "name": "Los Angeles Rams",
    "abbr": "LAR",
    "colors": [
      "#003594",
      "#FFA300"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1990s",
        "name": "St. Louis Rams"
      },
      {
        "era": "2000s",
        "name": "St. Louis Rams"
      },
      {
        "era": "2010s",
        "name": "St. Louis Rams"
      }
    ]
  },
  {
    "id": "dolphins",
    "name": "Miami Dolphins",
    "abbr": "MIA",
    "colors": [
      "#008E97",
      "#FC4C02"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "vikings",
    "name": "Minnesota Vikings",
    "abbr": "MIN",
    "colors": [
      "#4F2683",
      "#FFC62F"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "patriots",
    "name": "New England Patriots",
    "abbr": "NE",
    "colors": [
      "#002244",
      "#C60C30"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "saints",
    "name": "New Orleans Saints",
    "abbr": "NO",
    "colors": [
      "#D3BC8D",
      "#101820"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "giants",
    "name": "New York Giants",
    "abbr": "NYG",
    "colors": [
      "#0B2265",
      "#A71930"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "jets",
    "name": "New York Jets",
    "abbr": "NYJ",
    "colors": [
      "#125740",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "eagles",
    "name": "Philadelphia Eagles",
    "abbr": "PHI",
    "colors": [
      "#004C54",
      "#A5ACAF"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "steelers",
    "name": "Pittsburgh Steelers",
    "abbr": "PIT",
    "colors": [
      "#FFB612",
      "#101820"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "49ers",
    "name": "San Francisco 49ers",
    "abbr": "SF",
    "colors": [
      "#AA0000",
      "#B3995D"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "seahawks",
    "name": "Seattle Seahawks",
    "abbr": "SEA",
    "colors": [
      "#002244",
      "#69BE28"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "buccaneers",
    "name": "Tampa Bay Buccaneers",
    "abbr": "TB",
    "colors": [
      "#D50A0A",
      "#34302B"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "titans",
    "name": "Tennessee Titans",
    "abbr": "TEN",
    "colors": [
      "#0C2340",
      "#4B92DB"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "Houston Oilers"
      },
      {
        "era": "1970s",
        "name": "Houston Oilers"
      },
      {
        "era": "1980s",
        "name": "Houston Oilers"
      },
      {
        "era": "1990s",
        "name": "Houston Oilers"
      }
    ]
  },
  {
    "id": "commanders",
    "name": "Washington Commanders",
    "abbr": "WAS",
    "colors": [
      "#5A1414",
      "#FFB612"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "Washington"
      },
      {
        "era": "1970s",
        "name": "Washington"
      },
      {
        "era": "1980s",
        "name": "Washington"
      },
      {
        "era": "1990s",
        "name": "Washington"
      },
      {
        "era": "2000s",
        "name": "Washington"
      },
      {
        "era": "2010s",
        "name": "Washington"
      }
    ]
  }
];
