// Generated by scripts/etl/nhl.ts — do not edit by hand.
import type { FranchiseDef } from "@/engine/types";

export const NHL_FRANCHISES: FranchiseDef[] = [
  {
    "id": "bruins",
    "name": "Boston Bruins",
    "abbr": "BOS",
    "colors": [
      "#FFB81C",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "sabres",
    "name": "Buffalo Sabres",
    "abbr": "BUF",
    "colors": [
      "#003087",
      "#FFB81C"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "flames",
    "name": "Calgary Flames",
    "abbr": "CGY",
    "colors": [
      "#C8102E",
      "#F1BE48"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1970s",
        "name": "Atlanta Flames"
      }
    ]
  },
  {
    "id": "hurricanes",
    "name": "Carolina Hurricanes",
    "abbr": "CAR",
    "colors": [
      "#CC0000",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1980s",
        "name": "Hartford Whalers"
      },
      {
        "era": "1990s",
        "name": "Hartford Whalers"
      }
    ]
  },
  {
    "id": "blackhawks",
    "name": "Chicago Blackhawks",
    "abbr": "CHI",
    "colors": [
      "#CF0A2C",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "avalanche",
    "name": "Colorado Avalanche",
    "abbr": "COL",
    "colors": [
      "#6F263D",
      "#236192"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1980s",
        "name": "Quebec Nordiques"
      },
      {
        "era": "1990s",
        "name": "Quebec Nordiques"
      }
    ]
  },
  {
    "id": "bluejackets",
    "name": "Columbus Blue Jackets",
    "abbr": "CBJ",
    "colors": [
      "#002654",
      "#CE1126"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "stars",
    "name": "Dallas Stars",
    "abbr": "DAL",
    "colors": [
      "#006847",
      "#8F8F8C"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1960s",
        "name": "Minnesota North Stars"
      },
      {
        "era": "1970s",
        "name": "Minnesota North Stars"
      },
      {
        "era": "1980s",
        "name": "Minnesota North Stars"
      }
    ]
  },
  {
    "id": "redwings",
    "name": "Detroit Red Wings",
    "abbr": "DET",
    "colors": [
      "#CE1126",
      "#C0C0C0"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "oilers",
    "name": "Edmonton Oilers",
    "abbr": "EDM",
    "colors": [
      "#FF4C00",
      "#041E42"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "panthers",
    "name": "Florida Panthers",
    "abbr": "FLA",
    "colors": [
      "#C8102E",
      "#041E42"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "kings",
    "name": "Los Angeles Kings",
    "abbr": "LAK",
    "colors": [
      "#111111",
      "#A2AAAD"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "wild",
    "name": "Minnesota Wild",
    "abbr": "MIN",
    "colors": [
      "#154734",
      "#DDCBA4"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "canadiens",
    "name": "Montreal Canadiens",
    "abbr": "MTL",
    "colors": [
      "#AF1E2D",
      "#192168"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "predators",
    "name": "Nashville Predators",
    "abbr": "NSH",
    "colors": [
      "#FFB81C",
      "#041E42"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "devils",
    "name": "New Jersey Devils",
    "abbr": "NJD",
    "colors": [
      "#CE1126",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1970s",
        "name": "Colorado Rockies"
      }
    ]
  },
  {
    "id": "islanders",
    "name": "New York Islanders",
    "abbr": "NYI",
    "colors": [
      "#00539B",
      "#F47D30"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "rangers",
    "name": "New York Rangers",
    "abbr": "NYR",
    "colors": [
      "#0038A8",
      "#CE1126"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "senators",
    "name": "Ottawa Senators",
    "abbr": "OTT",
    "colors": [
      "#C2912C",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "flyers",
    "name": "Philadelphia Flyers",
    "abbr": "PHI",
    "colors": [
      "#F74902",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "penguins",
    "name": "Pittsburgh Penguins",
    "abbr": "PIT",
    "colors": [
      "#000000",
      "#FCB514"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "sharks",
    "name": "San Jose Sharks",
    "abbr": "SJS",
    "colors": [
      "#006D75",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "kraken",
    "name": "Seattle Kraken",
    "abbr": "SEA",
    "colors": [
      "#001628",
      "#99D9D9"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "blues",
    "name": "St. Louis Blues",
    "abbr": "STL",
    "colors": [
      "#002F87",
      "#FCB514"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "lightning",
    "name": "Tampa Bay Lightning",
    "abbr": "TBL",
    "colors": [
      "#002868",
      "#FFFFFF"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "mapleleafs",
    "name": "Toronto Maple Leafs",
    "abbr": "TOR",
    "colors": [
      "#00205B",
      "#FFFFFF"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "canucks",
    "name": "Vancouver Canucks",
    "abbr": "VAN",
    "colors": [
      "#00205B",
      "#00843D"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "goldenknights",
    "name": "Vegas Golden Knights",
    "abbr": "VGK",
    "colors": [
      "#B4975A",
      "#333F42"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "capitals",
    "name": "Washington Capitals",
    "abbr": "WSH",
    "colors": [
      "#041E42",
      "#C8102E"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ]
  },
  {
    "id": "jets",
    "name": "Winnipeg Jets",
    "abbr": "WPG",
    "colors": [
      "#041E42",
      "#004C97"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "2000s",
        "name": "Atlanta Thrashers"
      }
    ]
  },
  {
    "id": "ducks",
    "name": "Anaheim Ducks",
    "abbr": "ANA",
    "colors": [
      "#F47A38",
      "#000000"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1990s",
        "name": "Mighty Ducks of Anaheim"
      },
      {
        "era": "2000s",
        "name": "Mighty Ducks of Anaheim"
      }
    ]
  },
  {
    "id": "coyotes",
    "name": "Arizona Coyotes",
    "abbr": "ARI",
    "colors": [
      "#8C2633",
      "#E2D6B5"
    ],
    "activeEras": [
      "1960s",
      "1970s",
      "1980s",
      "1990s",
      "2000s",
      "2010s",
      "2020s"
    ],
    "aliases": [
      {
        "era": "1980s",
        "name": "Winnipeg Jets"
      },
      {
        "era": "1990s",
        "name": "Winnipeg Jets"
      },
      {
        "era": "2000s",
        "name": "Phoenix Coyotes"
      },
      {
        "era": "2010s",
        "name": "Phoenix Coyotes"
      }
    ]
  }
];
